### PR TITLE
Update tree + cosmetic

### PR DESCRIPTION
**Pull request by PierreR**
Hi,

Could you review these two commits ?

In the first one, I propose to update the tree instead of regenerate a new one whenever we submit a command.

The second one is cosmetic.

I would like to issue a third pull request. I am not convinced that managing a "progress" state on the node is the way to go. I would simply remove the spinning attribute when it is necessary in the line of my first commit.

I believe we have two different usages here that might be nicely refactor in a x-tag mixin. The first one is to show/hide the "icon-spinner" and the other one is to spin on/off the "icon-spinner".

As a note, I am not totally convinced by x-tags. I have found the doc quite awful and [the component code](https://github.com/mozilla/x-tag-elements/tree/xtag-v0.0.22) not so pretty.

It would be nice as well to establish some convention because the "this/that" ugly trick is confusing enough ;-) So in this pull request I took the liberty to favor "inline then" with "this/that" instead of defining another method (the main motivation is not to expose these callbacks too much).

Let me know what you think. I am not totally clear on what's best at the moment ...

You might be right thinking that wiping out the children nodes is actually more flexible.

 I look forward for your feedback. Thanks.

### CODE REVIEW

**Comment by whiteinge** [comment]
You're right that it will usually be best not to wipe out all children elements. In fact updating elements in place is the preferred behavior for d3. I'll look at this as soon as I get into the office (on my phone atm).

**Comment by whiteinge** [comment]
Looks good. Thanks for the changes and for fixing the minion detail placeholder. :)

Regarding the cosmetic changes, I would prefer to keep the trailing commas. I believe IE9 should handle these correctly now (when not in compat view or quirks mode, both of which are disabled in index.html). I'm in favor of removing the that=this scoping workaround.

Regarding X-Tags, it is young and the docs aren't great. That said, one nice thing is the source is small enough to read through in an hour or so.

**Comment by PierreR** [comment]
Ok, I will put back the training commas as soon as I have a chance (my editor was complaining as technically the syntax is faulty).

I myself prefer the comma first notation ala Haskell (https://github.com/PierreR/salt-ui/commit/97947d4f56265e4bc726be503818f38ae47ef944) but well never mind ;-)

It would be nice to write down  these conventions. You seem to prefer naming variable ala Python (as opposed to camelcase which is more usual in javascript) ?

Anyhow I will conform to whatever convention you decide to enforce.

About the "this/that" trick, I am quite curious to see what you will end up with. It is probably not convenient to force a method callback each time (which to me is as confusing). I have post on Q group about this:

https://groups.google.com/forum/?hl=en&fromgroups=#!searchin/q-continuum/this/q-continuum/mBCnyV6PoMw/2zlBEKPH-cMJ

**Comment by whiteinge** [comment]
Trailing commas were added to the spec in ES5 (woot). Hopefully you can silence those warnings in your editor somehow. For ES3 and JSON, I do agree with you that comma-first syntax is much more manageable. :)

I will certainly put together a style guide once the project is around the 0.7/0.8 release.

Thanks for the link to your mailing list post. This is a perennial problem with JS scoping. We should be able to come up with a better pattern once the pipeline from xtag -> formatter -> crystal -> d3 is more concrete.

**Comment by whiteinge** [comment]
Oh, and no biggie about adding those trailing commas back in. Send a pull req if you have time, or I'll get 'em as I circle back around to those files. It's not a big deal. The fixes you sent in are much more important. So thanks! :-D

**Pull request merged**
